### ISSUE TITLE
Can't build the decryptor.

### ISSUE THREAD

**Issue by forkoz** [talentraspel/GD-77#1]
So I have VS2015, 2017 doesn't want to install due to security certificates.

VS 2015 really hates this line:
data = ~(((data << 3) & 0b11111000) | ((data >> 5) & 0b00000111));

Didn't work on SharpDevelop either.

**Comment by talentraspel** [comment]
Please give the actual error message that VS2015 is telling you. Otherwise its hard to help.

You can try to split the statement into its parts to find the detailed cause. Maybe its just that VS2015 does not understand the binary value format 0bXXXXXXXX so you have to convert the values to decimal or hex to make the statement work with VS2015.

**Comment by forkoz** [comment]
It doesn't like the format, the | and complains about the parentheses.

) expected (CS1026) -  :61,42
; expected (CS1002) -  :61,51
Invalid expression term ')' (CS1525) -  :61,51
) expected (CS1026) -  :61,71
; expected (CS1002) -  :61,80
Invalid expression term ')' (CS1525) -  :61,80
; expected (CS1002) -  :61,81
Invalid expression term ')' (CS1525) -  :61,81
) expected (CS1026) -  :116,42
; expected (CS1002) -  :116,51
Invalid expression term ')' (CS1525) -  :116,51
) expected (CS1026) -  :116,71
; expected (CS1002) -  :116,80
Invalid expression term ')' (CS1525) -  :116,80
; expected (CS1002) -  :116,81
Invalid expression term ')' (CS1525) -  :116,81

**Comment by talentraspel** [comment]
You can try to split the statement into its parts to find the detailed cause.

**Comment by talentraspel** [comment]
And the binary literals are >= C++14. VS2015 should support them but perhaps your version is not current state or C++14 is not enabled.

So you can just try to replace the statement with:
data = ~(((data << 3) & 0xF8) | ((data >> 5) & 0x07));

**Comment by forkoz** [comment]
It worked for SharpDevelop to do that.

**Comment by forkoz** [comment]
close
