### ISSUE TITLE
The latest  updates in change log

### ISSUE THREAD

**Issue by sp2ong** [talentraspel/GD-77#20]
Kai,

I think the changelog 

https://github.com/talentraspel/GD-77/blob/master/GD-77_new_firmware/firmware_binaries/firmware.txt

will be faster to see what's new when it's written the other way around, i.e. the latest updates at the very beginning of the file. I suppose that with time the file will contain a lot of information about the changes so it will be very large.

It's just a small suggestion :-)

73 Waldek

**Comment by talentraspel** [comment]
Good idea. I'll take care of that with the next update. Thanks a lot.

**Comment by sp2ong** [comment]
OK thanks
